### ISSUE TITLE
using gpg short ids is a security issue

### ISSUE THREAD

**Issue by adrelanos** [rickard2/grsecurity-Debian-Installer#10]
```
gpg --recv-keys 6092693E
```

Using short key id's is bad for security, see:
http://www.asheesh.org/note/debian/short-key-ids-are-bad-news.html

I recommend using not just using long key id's, but the full key fingerprint.

**Comment by rickard2** [comment]
Thank you, I did not know about this issue. 

I'm an gpg expert, I've just followed the instructions found here: https://www.kernel.org/signature.html

Do you know the command to retrieve the key using the full fingerprint?

**Comment by adrelanos** [comment]
From https://www.kernel.org/signature.html. See...

```
Primary key fingerprint: 647F 2865 4894 E3BD 4571  99BE 38DB BDC8 6092 693E
```

Then just concatenate it.

```
gpg --recv-keys 647F28654894E3BD457199BE38DBBDC86092693E
```

I recommend to use the full fingerprint everywhere, consistently.
