### ISSUE TITLE
Support for 'make localmodconfig'

### ISSUE THREAD

**Issue by kellogs** [rickard2/grsecurity-Debian-Installer#4]
'make localmodconfig' parses the result of lsmod and turns modules into static and disables all others. It makes a very secure and light kernel, suitable for production.

it is recommended to plug all device to allow detection of the needed devices.

Do you think it would be worth giving a choice to the user, like: "Compile Kernel with:
(1) grsec + shared modules (default)
(2) grsec + static modules (make localmodconfig). In this case, please plug all your needed devices for detection.

Kind regards,
Kellogs

**Comment by rickard2** [comment]
Doesn't seem to be going anywhere
